Cette bibliotèque nous permettra de: <br>
-Charger les données <br>
-Manipuler les données <br>
-sauvegarder les données <br>

Quelque soient les types de données ils seront transformer en données numerique dans un tableau <br>


In [ ]:
import numpy as np

In [ ]:
np.__version__

'1.26.4'

In [ ]:
np?

In [ ]:
np.array([range(i,i+3) for i in [2,4,6]]) # liste imbriquée pour tableau mutidimentionnel

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

Pour créer un tableau avec numpy on écrit np.array([     ], dtype = 'le types de données qui sera stocké) <br>
- les données dans la table à l'instar des listes doivent être de même type

In [ ]:
np.array([1,3,4,12], dtype='float32')

array([ 1.,  3.,  4., 12.], dtype=float32)

- Création de tableaux avec valeurs initiales <br>
***np.zero(), np.ones(), np.full(), np.arrange, np(), np.random.random(), np.random(3,3), np.random.normal(), np.random.randint(), np.eye()**

In [ ]:
np.zeros((3,5),dtype= int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
np.ones((3,5)) # trois lignes et 5 colonnes

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.full((2,3), 3.14) # tableau avec deux lignes, 3 colonnes contenant uniquement avaleur 3.14

array([[3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14]])

In [ ]:
np.arange(0,20,2) # tableau contenant des valeurs de 0 à 20 avec un pas de 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.linspace(0,1,5) # tableau contenant 5 valeurs uniformément réparties entre 0 et 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.random.random((3,3))# nombre aléatoire compris entre 0 et 1 (3 lignes et 3 colonnes)

array([[0.55461623, 0.92128807, 0.02793167],
       [0.31920433, 0.31963956, 0.7129058 ],
       [0.94146284, 0.71791873, 0.26157423]])

In [ ]:
np.random.randint(1, 20, (3,3))# tableau 3x3 nombre aléatoire entre 1 et 20

array([[ 9, 12,  9],
       [17,  1, 19],
       [18, 17,  7]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.empty(3)

array([1., 1., 1.])

Connaître les types de données en numpy: <br>

**bool_, int_, intc, intp, int16, int32, int64, unit8 a 64, float_n float16 à 64, complex_, complex64, complex128**

## Fondamentaux des tableaux Numpy <br>
- **Accès aux tributs d'un tableau Numpy** (Pour connaître : la taille, la forme, l'occupation mémoire et le type de données)

In [ ]:
x1 = np.random.randint(10, size = 6)

In [ ]:
x2 = np.random.randint(10,size = (3,4))

In [ ]:
x3 = np.random.randint(10, size = (3,4,5))

In [ ]:
print(x1)

[5 5 3 1 6 9]


In [ ]:
print(x2)

[[4 5 2 8]
 [3 0 5 9]
 [0 6 8 8]]


In [ ]:
print(x3)

[[[1 3 5 9 4]
  [6 4 7 3 7]
  [9 3 0 4 3]
  [5 4 7 7 5]]

 [[9 5 8 1 2]
  [2 6 7 1 0]
  [1 3 1 3 1]
  [9 3 1 3 1]]

 [[1 4 2 5 2]
  [4 9 6 8 8]
  [0 6 4 1 4]
  [0 5 3 7 5]]]


In [ ]:
x4 = np.random.randint(10, size = (3,4,5,6)) #6 = nbre colonne, 5 = nbre ligne, 4 = nbre dimension, 3 = nbre dimension repeter 3 fois
x4

array([[[[0, 3, 9, 5, 9, 7],
         [1, 3, 8, 6, 0, 3],
         [6, 1, 3, 5, 2, 3],
         [0, 3, 0, 6, 5, 2],
         [5, 1, 1, 2, 5, 4]],

        [[7, 9, 9, 2, 2, 1],
         [2, 5, 2, 2, 0, 6],
         [1, 6, 5, 6, 8, 3],
         [3, 1, 5, 1, 5, 1],
         [5, 1, 9, 5, 8, 3]],

        [[7, 9, 2, 9, 5, 4],
         [2, 9, 1, 4, 6, 2],
         [6, 5, 6, 3, 5, 6],
         [3, 9, 2, 4, 1, 0],
         [2, 6, 9, 4, 6, 1]],

        [[8, 4, 7, 9, 5, 0],
         [2, 2, 6, 1, 0, 4],
         [6, 5, 3, 1, 6, 3],
         [8, 2, 9, 1, 5, 1],
         [4, 9, 9, 5, 3, 9]]],


       [[[4, 3, 4, 3, 1, 5],
         [3, 1, 9, 4, 4, 0],
         [5, 5, 2, 2, 2, 9],
         [3, 4, 8, 9, 7, 3],
         [8, 8, 6, 3, 8, 8]],

        [[5, 4, 7, 9, 8, 3],
         [3, 5, 5, 8, 0, 4],
         [7, 3, 3, 3, 3, 7],
         [3, 3, 1, 7, 5, 1],
         [8, 9, 9, 6, 5, 6]],

        [[6, 7, 9, 7, 2, 2],
         [7, 6, 3, 1, 2, 9],
         [4, 4, 1, 6, 9, 5],
         [5, 2, 0, 6, 8, 1],


In [ ]:
print("x1 ndim :", x1.ndim)
print("x1 shape :", x1.shape)
print("x1 size :", x1.size)
print("x1 dtype :", x1.dtype)

x1 ndim : 1
x1 shape : (6,)
x1 size : 6
x1 dtype : int64


In [ ]:
print("x3 ndim :", x3.ndim)
print("x3 shape :", x3.shape)
print("x3 size :", x3.size)
print("x3 dtype :", x3.dtype)

x3 ndim : 3
x3 shape : (3, 4, 5)
x3 size : 60
x3 dtype : int64


In [ ]:
## connaître la taille en octets et taille totale occupé en memoire
print("itemsize :", x3.itemsize, "bytes")
print("nbytes :", x3.nbytes, "bytes")

itemsize : 8 bytes
nbytes : 480 bytes


- **Index de tableaux et accès à un élément:** <br>
Pour lire, écrire la valeur de chaque élément individual

In [ ]:
x1[1]

5

In [ ]:
print(x2)
x2[1,2] # ligne 2 et colonne 3 car en python on commence par compter à 0 [debut,fin,nbre de pas]

[[4 5 2 8]
 [3 0 5 9]
 [0 6 8 8]]


5

In [ ]:
print(x1)
x1[-2] # comptage à partir du dernier chiffre avant dernier élément -2

[5 5 3 1 6 9]


6

In [ ]:
print(x2)
x2[1,-2] # deuxième ligne et l'avant dernier élément de la ligne

[[4 5 2 8]
 [3 0 5 9]
 [0 6 8 8]]


5

In [ ]:
print(x3)
print("séparation")
x3[1,-2] # deuxième dimension et avant denière ligne

[[[1 3 5 9 4]
  [6 4 7 3 7]
  [9 3 0 4 3]
  [5 4 7 7 5]]

 [[9 5 8 1 2]
  [2 6 7 1 0]
  [1 3 1 3 1]
  [9 3 1 3 1]]

 [[1 4 2 5 2]
  [4 9 6 8 8]
  [0 6 4 1 4]
  [0 5 3 7 5]]]
séparation


array([1, 3, 1, 3, 1])

In [ ]:
# changement de valeur
x3[1,-2] = np.array([2,3,4,7,10])

print(x3[1])
x3[1,-2]


[[ 9  5  8  1  2]
 [ 2  6  7  1  0]
 [ 2  3  4  7 10]
 [ 9  3  1  3  1]]


array([ 2,  3,  4,  7, 10])

In [ ]:
x3[0]= 3.14 # troncage de 3.14 à 3 car nombre entier
print(x3)

[[[ 3  3  3  3  3]
  [ 3  3  3  3  3]
  [ 3  3  3  3  3]
  [ 3  3  3  3  3]]

 [[ 9  5  8  1  2]
  [ 2  6  7  1  0]
  [ 2  3  4  7 10]
  [ 9  3  1  3  1]]

 [[ 1  4  2  5  2]
  [ 4  9  6  8  8]
  [ 0  6  4  1  4]
  [ 0  5  3  7  5]]]


- **Tranchage d'un tableau :**<br>
Obtenir et créer de petits sous-tableaux à partir d'un grand tableau

>**Sous tableau à une dimension**



In [ ]:
# x[start:end:step]
print(x1)
x1[:3] # les trois premier élément

[5 5 3 1 6 9]


array([5, 5, 3])

In [ ]:
x1[3:] # à partir de l'index 3

array([1, 6, 9])

In [ ]:
x1[3:5]

array([1, 6])

In [ ]:
x1[::2] # pas de 2

array([5, 3, 6])



>**Sous-tableau à plusieurs dimension**


In [ ]:
#La tranche séparer par des virgule
print(x3,"\n")
print("séparation \n")
x3[:2,:2,:3] # récuperation de la première et deuxième dimension, recuperation des deux premières lignes et trois colonnes

[[[ 3  3  3  3  3]
  [ 3  3  3  3  3]
  [ 3  3  3  3  3]
  [ 3  3  3  3  3]]

 [[ 9  5  8  1  2]
  [ 2  6  7  1  0]
  [ 2  3  4  7 10]
  [ 9  3  1  3  1]]

 [[ 1  4  2  5  2]
  [ 4  9  6  8  8]
  [ 0  6  4  1  4]
  [ 0  5  3  7  5]]] 

séparation 



array([[[3, 3, 3],
        [3, 3, 3]],

       [[9, 5, 8],
        [2, 6, 7]]])

In [ ]:
import numpy as np
arr = np.array([-1,-4,2,56,-1,0])

In [ ]:
# note des étudiants
arr_note = np.array([12,11,9,18,6,17,8])

In [ ]:
print("la moyenne :", arr_note.mean())
print("minimum:", arr_note.min())
print("maximum:", arr_note.max())
print("nombre étudiant ayant la moyenne", len(arr_note[arr_note>=arr_note.mean()]))# methode avec len
print("nomre étudiant ayant inferieure à la moyenne générale", np.sum(arr_note>arr_note.mean())) # methode avec sum de numpy

la moyenne : 11.571428571428571
minimum: 6
maximum: 18
nombre étudiant ayant la moyenne 3
nomre étudiant ayant inferieure à la moyenne générale 3


In [ ]:
# Change les notes inférieure à 10 en leur faisant plus 2
arr_note[arr_note<10] = arr_note[arr_note<10] + 2
arr_note

array([12, 11, 11, 18,  8, 17, 10])

In [ ]:
print("nombre étudiant ayant la moyenne", len(arr_note[arr_note>=10]))

nombre étudiant ayant la moyenne 6


- **Reformatage d'un tableau :** <br>
Pour changer de forme et la géometrie d'un tableau


range(0, 2)

- **Compactage et éclatement d'un tableau :** <br>
Pour combiner plusieurs tableaux en un seul et pour en répartir un en plusieur